### ISSUE TITLE
proxyが抜けれない

### ISSUE THREAD

**Issue by Yusuke96** [Yusuke96/bbt#20]
`Client()`の引数に
```py
Client(proxy='proxy_url:[port]')
```
みたいにプロキシサーバの情報を渡すことでプロキシを設定できるみたい。
これは成功したけど、そのあとの
```py
client.run(TOKEN)
```
の部分で止まる。

これはdiscord.pyには正しくプロキシの設定を反映できてはいるけど、
プロキシサーバがdiscord.pyからのリクエストを拒否しているということ？？
`client.run()`がどんなプロトコルでdiscordと通信するかわかんないけど、
大学のプロキシが許可してないプロトコルだと詰んだ可能性もある、、、

とりあえず行き詰まったので、このissueは放置して先に実装を進めることにするw

**Comment by arusuDev** [comment]
proxy環境外で運用するようにした。
