### ISSUE TITLE
Yasuo Bot 〜社畜への道〜

### ISSUE THREAD

**Issue by Yusuke96** [Yusuke96/bbt#22]
PythonのDiscord botを無料で24時間稼働させるって記事があった↓
https://qiita.com/v2okimochi/items/f8eadfd668c36ad94277
運用段階になったら試してみよう

**Comment by arusuDev** [comment]
朝起きてメール見たらタイトルで笑ってしまったわｗ

**Comment by Yusuke96** [comment]
サーバにPython3.xの環境を構築してbotを動かせるようになった。
