### ISSUE TITLE
BOTの認証が上手く行ってない

### ISSUE THREAD

**Issue by Yusuke96** [Yusuke96/bbt#7]
HTTP401が出る。
ぱっと思いつく原因として
*BBTの権限設定が保存できていない？
*Discordのサーバ側からもBBTに権限をあげる許可が必要？
とかかな、、

**Comment by arusuDev** [comment]
結局原因わからずじまいだったけど、tokenをGithubに直接Upしてしまったのはまずかった説あるね。  
再生成+権限付与で解決。
